### PR TITLE
add implicitUtilities to schemaOptions

### LINKED ISSUE #34: when I use the property like this "implicitUtilities: 'utils/*.css'", it comes an error
when I try to set the property “implicitUtilties“, I got an error like this
image
so I add the statements in your plugin, and it works well
````
implicitUtilities: [_.isBoolean, _.isString, function(pattern) {
    return _.isArray(pattern) && _.every(pattern, _.isString);
  }],
````
Is there anything wrong about the plugin?

### PR DESCRIPTION
**Pull request by plinton**
Fixes #34

### CODE REVIEW

**Comment by plinton** [comment]
Hey @simonsmith it looks like postcss-less does not support node 4. Node 4 is well past it's support date so it seems safe to drop support.

**Comment by simonsmith** [comment]
Hey @plinton, thanks for the PR. You are indeed correct. I'll merge this and update the build config

**Comment by simonsmith** [comment]
@lachieh I'll get this done asap

**Comment by simonsmith** [comment]
Released - https://www.npmjs.com/package/stylelint-selector-bem-pattern/v/2.1.0

Sorry for the delay!

**Comment by lachieh** [comment]
Awesome! Thanks so much!

**Pull request merged**
